server:
  host: "localhost"
  port: 8080

session:
  duration: "24h"
  idle_timeout: "60m"
  cookie_name: "sessid"
  token_secret: ""

targets:
  "/8081": "http://localhost:8081"

stubs:
  storage:
    #type: "file"
    type: "redis"
    #path: "stubfiles"
    path: "redis://localhost:6379/0"
    cache:
      enabled: True
      expiration_interval: "30m"
      cleanup_interval: "60m"
