[server]
host = "localhost"
port = 8080

[session]
duration = "24h"
idle_timeout = "60m"
cookie_name = "sessid"
token_secret = ""
userid_field = "username"

[targets]
"/8081" = "http://localhost:8081"

[stubs]

[stubs.storage]
type = "redis"
path = "redis://localhost:6379/0"

[stubs.storage.cache]
enabled = false
expiration_interval = "30m"
cleanup_interval = "60m"